# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iFfuGH4T2A0fnbw23y8MMFnGukvzftsz
"""

import math

def hitung_jarak(x1, x2, x3, y1, y2, y3):
    return math.sqrt(
        (x1 - y1)**2 +
        (x2 - y2)**2 +
        (x3 - y3)**2
    )

# SKENARIO 1
print("SKENARIO 1")

x1 = 7
x2 = -2
x3 = 4

jarakA = hitung_jarak(x1, x2, x3, 2, 1, 3)
jarakB = hitung_jarak(x1, x2, x3, 1, -4, 6)
jarakC = hitung_jarak(x1, x2, x3, -2, 3, -2)

if jarakA < jarakB and jarakA < jarakC:
    cluster = "Cluster A"
elif jarakB < jarakA and jarakB < jarakC:
    cluster = "Cluster B"
elif jarakC < jarakA and jarakC < jarakB:
    cluster = "Cluster C"
else:
    cluster = "Cluster Tidak Diketahui"

print("Jarak A =", jarakA)
print("Jarak B =", jarakB)
print("Jarak C =", jarakC)
print(cluster)

print()

# SKENARIO 2
print("SKENARIO 2")

x1 = 2
x2 = -5
x3 = 7

jarakA = hitung_jarak(x1, x2, x3, 2, 1, 3)
jarakB = hitung_jarak(x1, x2, x3, 1, -4, 6)
jarakC = hitung_jarak(x1, x2, x3, -2, 3, -2)

if jarakA < jarakB and jarakA < jarakC:
    cluster = "Cluster A"
elif jarakB < jarakA and jarakB < jarakC:
    cluster = "Cluster B"
elif jarakC < jarakA and jarakC < jarakB:
    cluster = "Cluster C"
else:
    cluster = "Cluster Tidak Diketahui"

print("Jarak A =", jarakA)
print("Jarak B =", jarakB)
print("Jarak C =", jarakC)
print(cluster)

print()

# SKENARIO 3
print("SKENARIO 3")

x1 = -1
x2 = 3
x3 = -2

jarakA = hitung_jarak(x1, x2, x3, 2, 1, 3)
jarakB = hitung_jarak(x1, x2, x3, 1, -4, 6)
jarakC = hitung_jarak(x1, x2, x3, -2, 3, -2)

if jarakA < jarakB and jarakA < jarakC:
    cluster = "Cluster A"
elif jarakB < jarakA and jarakB < jarakC:
    cluster = "Cluster B"
elif jarakC < jarakA and jarakC < jarakB:
    cluster = "Cluster C"
else:
    cluster = "Cluster Tidak Diketahui"

print("Jarak A =", jarakA)
print("Jarak B =", jarakB)
print("Jarak C =", jarakC)
print(cluster)

