# -*- coding: utf-8 -*-
"""untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/khalisairfani-netizen/b2c4671774fcb5d54edd0fcd75d2ba7a/untitled6.ipynb
"""

K1 = "Saya tak 'kan menyerah."
K2 = 'Ia berkata, "Aku menyayangimu."'
K3 = "\"Coba jelaskan pengertian 'cross-validation' dalam Machine Learning!\""
K4 = "Surat keputusan itu bernomor 62/UN.34/19/2023."

print(K1)
print(K2)
print(K3)
print(K4)

